// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionButtonSmall': string;
  'actions': string;
  'icon': string;
  'index': string;
  'inputText': string;
  'inputTextRoot': string;
  'name': string;
  'row': string;
  'size': string;
}
export const cssExports: CssExports;
export default cssExports;
