// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionButtonSmall': string;
  'appContainer': string;
  'appContainerDisabled': string;
  'icon': string;
  'inputText': string;
  'inputTextRoot': string;
}
export const cssExports: CssExports;
export default cssExports;
